### PR TITLE
UI UPDATE: Update Card Layout - Change Header and Load Color

### PR DESCRIPTION
**Pull request by TanBeige**
Let me know if you have any feedback. I think NFT's are on fire right now and lighter-friendlier colors will bring more people to ergo NFT's. If you like this change, I will be adding more as this is a great start to Ergo's ecosystem.

### CODE REVIEW

**Comment by TanBeige** [comment]
https://user-images.githubusercontent.com/9562512/128752581-777a156a-8d44-4947-9c50-8ac7ebbdb4fd.mp4

**Comment by TanBeige** [comment]
Header Changed to white based off community response:
ergoauctionwhite

**Comment by anon-real** [comment]
I think auction cards should be the same size independent of the description. Currently, they are in different sizes.

**Comment by TanBeige** [comment]
@anon-real Should be good to go now 👍

**Comment by anon-real** [comment]
@TanBeige thanks for the change. Now there is a horizontal scroll which isn't desirable:
scroll-

**Comment by TanBeige** [comment]
> @TanBeige thanks for the change. Now there is a horizontal scroll which isn't desirable:
> scroll-

Fixed this by lowering the amount of cards per row - I was too bold to try something like that without layout problems.

Should be good now, let me know if anything else pops up.

**Comment by anon-real** [comment]
@TanBeige Great, thanks!
It is up here: https://newui.ergoauctions.org/
I am sending it to the artist community to give their feedback and then I'll merge it to master.
Please send me your address to donate you some ERGs.

**Pull request merged**
