### PR TITLE
Updated header and removed sidebar from large screen

### PR DESCRIPTION
**Pull request by yashvantvala**

### CODE REVIEW

**Comment by anon-real** [comment]
Please create a PR based of branch "new"

**Comment by anon-real** [comment]
@yashvantvala Please let me know if you encounter any problems. Any ETA?

**Comment by yashvantvala** [comment]
There are couple of bugs and issues here in the code and also codebase is not good. Let me know if we can have a meeting so we can discuss more about this

**Comment by anon-real** [comment]
> There are couple of bugs and issues here in the code and also codebase is not good. Let me know if we can have a meeting so we can discuss more about this

We can chat on discord, please DM me when you can. Any contributions for refactoring and improving the codebase will be rewarded.

**Pull request closed without merging**
