### PR TITLE
Add Search Functionality

### PR DESCRIPTION
**Pull request by sepehr2github**
Now, Users should be able to search in description and artist's wallet

### CODE REVIEW

**Comment by sepehr2github** [comment]
https://user-images.githubusercontent.com/46657145/131243791-52f245a7-3456-4fc9-8915-85d339b0bc31.mp4

**Comment by anon-real** [comment]
Seems good! A few notes:
- It does not have a proper behavior when there are no results for the searched string
- Filters do not work when something is searched. Not a big deal but it is better for filters to work to for example sort results based on ERG value, ...
- Can you also search for the bidder's address?
- It would be much nicer for the searched string to be added to the URL as a query string so people can share the page
- And the text will be: "Search in the description, artist address, and bidder's address"

**Comment by sepehr2github** [comment]
@anon-real . Thanks For your feedback. I will Trying to Fix all reported issues and send you a new pull request as fast as I can

**Comment by anon-real** [comment]
Already merged with "new".

**Pull request closed without merging**
