### PR TITLE
add notification center

### PR DESCRIPTION
**Pull request by sepehr2github**
- notification center added
- notification icon unread badge added
- disappear badge after read notification added

### CODE REVIEW

**Comment by sepehr2github** [comment]
Let me know if any changes needed.

**Comment by anon-real** [comment]
Thanks! Please resolve conflicts.
Also, how to add a notification?

**Comment by sepehr2github** [comment]
@anon-real  So you can add your notifications to "data" array in notification key (local Storage), example:
`{
data:[{message:'test',link:'https://test.com'}]
unread:1
}`

**Comment by anon-real** [comment]
It shouldn't need a refresh to show the notification badge.
Also, one nice addition is to show a sticky message when unread is increased (new notifications are added) that "You have new notifications"

**Comment by anon-real** [comment]
Also, let's also show the time of the notification. So the new notification json will be sth like:
`{ data:[{message:'test',link:'https://test.com', status: 'error', time: 13438347374}], unread:1 }`

**Comment by anon-real** [comment]
Also, please reverse the list before showing. Latest should be first.

**Comment by anon-real** [comment]
Also, only show the last "unread" notification. If user wants to see previous notifications, there should be a button for that "load read notifications"

**Comment by sepehr2github** [comment]
@anon-real maybe we can add new border with new tag :). something like discord new messsage

**Comment by sepehr2github** [comment]
I will send new pull request with your desired features.

**Comment by anon-real** [comment]
> @anon-real maybe we can add new border with new tag :). something like discord new messsage

That is also fine. However, notifications can grow over time to hundreds.
Also, I think it is good to fix the modal height and add scroll instead of it grow with notifications.

**Comment by anon-real** [comment]
@sepehr2github I've added a 'addNotification' method in helper.js. You don't need to add that.

**Comment by anon-real** [comment]
@sepehr2github Also, this may help, not sure though: https://stackoverflow.com/questions/26974084/listen-for-changes-with-localstorage-on-the-same-window

**Pull request merged**
